#!/usr/bin/env bash


echo "test5" > test.txt

mkdir .git/hooks/
cat > .git/hooks/pre-commit <<'EOF'
#!/bin/sh

echo "generated by pre-commit hook" > th.txt
git add th.txt
EOF

chmod +x .git/hooks/pre-commit
rm .git/HEAD

exit 0
