#!/usr/bin/env bash


echo "test2" > test.txt

mkdir .git/hooks/
cat > .git/hooks/pre-commit <<'EOF'
#!/bin/sh

echo "generated by pre-commit hook" > test.txt
git add test.txt
EOF

chmod +x .git/hooks/pre-commit

exit 0
